package com.example.listofstreetfood

import java.lang.ArithmeticException
import java.lang.Exception
import kotlin.math.floor

fun main() {
    /*
    val stringList : List<String> = listOf("Denis","Elli","Rob","Bob")
    val mixedType : List<Any> = listOf("Denis",1,3,"ROb","Frank")

/   }
// ---------- SAME THING CAN BE WRITTEN AS  WHEN APPROACH -------------------------------------
    for (value in mixedType) {
        when (value) {
            is Int -> println("Integer is : $value")
            is Double -> println("Double is : $value with floor ${floor(value)}")
            is String -> println("String is : $value with length ${value.length}")
            else -> println("Error")
        }
    }


    // ---------- SaFE TYPE CASTING -------------------------------------
    val str1: Any = 1234
    val castingType:String? = str1 as? String
    println("type casted integer to sting is ${castingType}") // Prints null




 // ---------- Safe CASTING OPERATOR as? -------------------------------------

val location:Any = "Kotlin"
val safeString: String? =  location as? String
val safeInt:Int? = location as? Int
    println(safeInt) // Null
    println(safeString)  // Kotlin
    // Return  the answer safely



    // ---------- Exception Handling -------------------------------------
                // THROWABLE CLASS //
    // ->  Try ( if exception is ok  Catch block wont appear )
    // - >  Catch ( if error occur in try catch will be executed )
    // -> Finally ( it is executed weather exception  is handle or not . to  executed important code)
    //-> Throw (Allows to  throw exception explicitly )

    try {
        val a = IntArray(5)
        a[5] = 10/0
    } catch (e:ArithmeticException){
        println("Arithmetic error")
    } catch (e:ArrayIndexOutOfBoundsException){
        println("Array IndexOutof Bond exception")
    }catch (e:Exception){
        println("Parent exception Class")
    }
    println("Print code after they catch")


                                // FINALLY EXCEPTION//
    try {
        val data:Float = 10/3f
        println(data)
    }catch (e:NullPointerException){
        println(e)
    } finally {
        println("Finally Block is always executed") // Finally always executes
    }
    println("below Code")
     */

                                            // THROW EXCEPTION//

}
